# Dockerfile.base
FROM python:3.12-slim

WORKDIR /app

# Install shared dependencies for all services
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN apt update && apt install -y curl && rm -rf /var/lib/apt/lists/*

COPY . .

CMD ["python", "directory_service.py"]
